/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WormholeBridge {
  export type TokenTransferStruct = {
    payloadID: BigNumberish;
    recipient: BytesLike;
  };

  export type TokenTransferStructOutput = [
    payloadID: bigint,
    recipient: string
  ] & { payloadID: bigint; recipient: string };
}

export interface WormholeBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONSISTENCY_LEVEL"
      | "GAS_LIMIT"
      | "MESSAGE_TIME_OUT_SECONDS"
      | "circleIntegration"
      | "decodePayload"
      | "getMessageFee"
      | "getSourceAddress"
      | "getWormholeChainId"
      | "policy"
      | "pullPolicy"
      | "pushPolicy"
      | "quoteEVMDeliveryCost"
      | "receiveSolanaMessage"
      | "receiveWormholeMessages"
      | "redeemTransferWithPayload"
      | "registerSender"
      | "relayer"
      | "renouncePolicy"
      | "sendMessageToEvm"
      | "sendMessageToSolana"
      | "tokenBridge"
      | "transferCrossChain"
      | "wormhole"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReceiveMessage"
      | "TransferToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONSISTENCY_LEVEL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GAS_LIMIT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_TIME_OUT_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circleIntegration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decodePayload",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSourceAddress",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWormholeChainId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pullPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteEVMDeliveryCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveSolanaMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveWormholeMessages",
    values: [BytesLike, BytesLike[], BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemTransferWithPayload",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSender",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renouncePolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageToEvm",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageToSolana",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferCrossChain",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "wormhole", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CONSISTENCY_LEVEL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GAS_LIMIT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_TIME_OUT_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circleIntegration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodePayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSourceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWormholeChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pullPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pushPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteEVMDeliveryCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveSolanaMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveWormholeMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemTransferWithPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renouncePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageToEvm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageToSolana",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCrossChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wormhole", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiveMessageEvent {
  export type InputTuple = [
    sender: AddressLike,
    sourceChain: BigNumberish,
    sourceAddress: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    sourceChain: bigint,
    sourceAddress: string
  ];
  export interface OutputObject {
    sender: string;
    sourceChain: bigint;
    sourceAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferTokenEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WormholeBridge extends BaseContract {
  connect(runner?: ContractRunner | null): WormholeBridge;
  waitForDeployment(): Promise<this>;

  interface: WormholeBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONSISTENCY_LEVEL: TypedContractMethod<[], [bigint], "view">;

  GAS_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MESSAGE_TIME_OUT_SECONDS: TypedContractMethod<[], [bigint], "view">;

  circleIntegration: TypedContractMethod<[], [string], "view">;

  decodePayload: TypedContractMethod<
    [encodedMessage: BytesLike],
    [WormholeBridge.TokenTransferStructOutput],
    "view"
  >;

  getMessageFee: TypedContractMethod<[], [bigint], "view">;

  getSourceAddress: TypedContractMethod<
    [tokenAddress: BytesLike, sourceChain: BigNumberish],
    [string],
    "view"
  >;

  getWormholeChainId: TypedContractMethod<[], [bigint], "view">;

  policy: TypedContractMethod<[], [string], "view">;

  pullPolicy: TypedContractMethod<[], [void], "nonpayable">;

  pushPolicy: TypedContractMethod<
    [newPolicy_: AddressLike],
    [void],
    "nonpayable"
  >;

  quoteEVMDeliveryCost: TypedContractMethod<
    [targetChain: BigNumberish],
    [bigint],
    "view"
  >;

  receiveSolanaMessage: TypedContractMethod<
    [_whMessage: BytesLike],
    [void],
    "payable"
  >;

  receiveWormholeMessages: TypedContractMethod<
    [
      payload: BytesLike,
      arg1: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "payable"
  >;

  redeemTransferWithPayload: TypedContractMethod<
    [encodedVM: BytesLike],
    [void],
    "nonpayable"
  >;

  registerSender: TypedContractMethod<
    [sourceChain: BigNumberish, sourceAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  renouncePolicy: TypedContractMethod<[], [void], "nonpayable">;

  sendMessageToEvm: TypedContractMethod<
    [
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _marketId: BigNumberish,
      _answerId: BigNumberish,
      _bettingKey: BigNumberish,
      targetChain: BigNumberish,
      targetAddress: AddressLike
    ],
    [void],
    "payable"
  >;

  sendMessageToSolana: TypedContractMethod<
    [
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _marketId: BigNumberish,
      _answerId: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  tokenBridge: TypedContractMethod<[], [string], "view">;

  transferCrossChain: TypedContractMethod<
    [
      _recipient: AddressLike,
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _targetChain: BigNumberish,
      _targetAddress: BytesLike
    ],
    [void],
    "payable"
  >;

  wormhole: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONSISTENCY_LEVEL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAS_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MESSAGE_TIME_OUT_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "circleIntegration"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decodePayload"
  ): TypedContractMethod<
    [encodedMessage: BytesLike],
    [WormholeBridge.TokenTransferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSourceAddress"
  ): TypedContractMethod<
    [tokenAddress: BytesLike, sourceChain: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWormholeChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pullPolicy"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pushPolicy"
  ): TypedContractMethod<[newPolicy_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "quoteEVMDeliveryCost"
  ): TypedContractMethod<[targetChain: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveSolanaMessage"
  ): TypedContractMethod<[_whMessage: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "receiveWormholeMessages"
  ): TypedContractMethod<
    [
      payload: BytesLike,
      arg1: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "redeemTransferWithPayload"
  ): TypedContractMethod<[encodedVM: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerSender"
  ): TypedContractMethod<
    [sourceChain: BigNumberish, sourceAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renouncePolicy"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendMessageToEvm"
  ): TypedContractMethod<
    [
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _marketId: BigNumberish,
      _answerId: BigNumberish,
      _bettingKey: BigNumberish,
      targetChain: BigNumberish,
      targetAddress: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendMessageToSolana"
  ): TypedContractMethod<
    [
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _marketId: BigNumberish,
      _answerId: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "tokenBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferCrossChain"
  ): TypedContractMethod<
    [
      _recipient: AddressLike,
      _bettingToken: AddressLike,
      _amount: BigNumberish,
      _targetChain: BigNumberish,
      _targetAddress: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "wormhole"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiveMessage"
  ): TypedContractEvent<
    ReceiveMessageEvent.InputTuple,
    ReceiveMessageEvent.OutputTuple,
    ReceiveMessageEvent.OutputObject
  >;
  getEvent(
    key: "TransferToken"
  ): TypedContractEvent<
    TransferTokenEvent.InputTuple,
    TransferTokenEvent.OutputTuple,
    TransferTokenEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiveMessage(address,uint16,bytes32)": TypedContractEvent<
      ReceiveMessageEvent.InputTuple,
      ReceiveMessageEvent.OutputTuple,
      ReceiveMessageEvent.OutputObject
    >;
    ReceiveMessage: TypedContractEvent<
      ReceiveMessageEvent.InputTuple,
      ReceiveMessageEvent.OutputTuple,
      ReceiveMessageEvent.OutputObject
    >;

    "TransferToken(address,uint256)": TypedContractEvent<
      TransferTokenEvent.InputTuple,
      TransferTokenEvent.OutputTuple,
      TransferTokenEvent.OutputObject
    >;
    TransferToken: TypedContractEvent<
      TransferTokenEvent.InputTuple,
      TransferTokenEvent.OutputTuple,
      TransferTokenEvent.OutputObject
    >;
  };
}
