/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITokenMinterInterface extends Interface {
  getFunction(
    nameOrSignature: "burnLimitsPerMessage" | "remoteTokensToLocalTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burnLimitsPerMessage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteTokensToLocalTokens",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "burnLimitsPerMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remoteTokensToLocalTokens",
    data: BytesLike
  ): Result;
}

export interface ITokenMinter extends BaseContract {
  connect(runner?: ContractRunner | null): ITokenMinter;
  waitForDeployment(): Promise<this>;

  interface: ITokenMinterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnLimitsPerMessage: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  remoteTokensToLocalTokens: TypedContractMethod<
    [sourceIdHash: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnLimitsPerMessage"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "remoteTokensToLocalTokens"
  ): TypedContractMethod<[sourceIdHash: BytesLike], [string], "view">;

  filters: {};
}
